// ── Shared PDF styles ─────────────────────────────────────────────────────────

const BASE_STYLES = `
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    font-size: 11pt; color: #111; padding: 40px 48px; max-width: 900px; margin: auto;
  }
  header { border-bottom: 2px solid #111; padding-bottom: 14px; margin-bottom: 28px; }
  header h1 { font-size: 20pt; font-weight: 700; letter-spacing: -0.02em; }
  header p  { font-size: 10pt; color: #555; margin-top: 4px; }
  section   { margin-bottom: 24px; }
  h2 {
    font-size: 10pt; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase;
    color: #555; border-bottom: 1px solid #e4e4e4; padding-bottom: 5px; margin-bottom: 10px;
  }
  h3 { font-size: 10.5pt; font-weight: 600; margin: 12px 0 4px; }
  p  { line-height: 1.65; }
  ul { padding-left: 18px; }
  li { margin-bottom: 5px; line-height: 1.55; }
  table { width: 100%; border-collapse: collapse; font-size: 10.5pt; }
  th {
    text-align: left; font-size: 9pt; font-weight: 600; letter-spacing: 0.04em;
    text-transform: uppercase; color: #555; padding: 6px 10px;
    background: #f7f7f7; border-bottom: 1px solid #ddd;
  }
  td { padding: 7px 10px; border-bottom: 1px solid #f0f0f0; vertical-align: top; }
  tr:last-child td { border-bottom: none; }
  .meta-row { display: flex; gap: 24px; margin-bottom: 4px; font-size: 10pt; color: #444; }
  .meta-row span strong { color: #111; }
  @media print { body { padding: 0; } section { page-break-inside: avoid; } }
`;

const PRINT_BAR = `
  <div id="__pbar__" style="position:fixed;bottom:0;left:0;right:0;background:#111;color:#fff;
    font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;font-size:12px;
    padding:10px 20px;display:flex;align-items:center;justify-content:space-between;z-index:9999;">
    <span>Press <strong>⌘P</strong> / <strong>Ctrl+P</strong> and choose <em>Save as PDF</em></span>
    <button onclick="document.getElementById('__pbar__').style.display='none';window.print();"
      style="background:#fff;color:#111;border:none;padding:6px 16px;border-radius:6px;
      cursor:pointer;font-size:12px;font-weight:600;">Print / Save PDF</button>
  </div>`;

function openPdf(html: string) {
  const withBar = html.replace("</body>", `${PRINT_BAR}</body>`);
  const blob = new Blob([withBar], { type: "text/html" });
  const url = URL.createObjectURL(blob);
  window.open(url, "_blank");
  setTimeout(() => URL.revokeObjectURL(url), 60_000);
}

function esc(s: string) {
  return String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
}

function plainTextPdf(title: string, subtitle: string, text: string) {
  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const body = sec("Output", `<p style="white-space:pre-wrap;line-height:1.7;color:#333">${esc(text)}</p>`);
  openPdf(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><title>${esc(title)}</title><style>${BASE_STYLES}</style></head><body><header><h1>${esc(title)}</h1><p>${esc(subtitle)} · Generated by Shinko1 · ${date}</p></header>${body}</body></html>`);
}

function sec(title: string, content: string) {
  return `<section><h2>${title}</h2>${content}</section>`;
}

function bul(items: string[]) {
  return `<ul>${items.map((i) => `<li>${i}</li>`).join("")}</ul>`;
}

// ── Summarise types ───────────────────────────────────────────────────────────
interface Participant { name: string; role: string }
interface ExistingSolution { solution: string; context: string }
interface NextStep { action: string; owner: string; due: string }

interface SummariseOutput {
  participants?: Participant[];
  what_went_well?: string[];
  what_needs_work?: string[];
  what_is_not_needed?: string[];
  existing_solutions_to_use?: ExistingSolution[];
  next_steps?: NextStep[];
  summary?: string;
  transcript_condensed?: string;
}

function section(title: string, content: string) {
  return `
    <section>
      <h2>${title}</h2>
      ${content}
    </section>`;
}

function bullets(items: string[]) {
  return `<ul>${items.map((i) => `<li>${i}</li>`).join("")}</ul>`;
}

export function exportSummarisePdf(raw: string, clientName = "Meeting") {
  let d: SummariseOutput;
  try { d = JSON.parse(raw); } catch { return plainTextPdf(`${clientName} — Meeting Summary`, "Meeting Summary", raw); }

  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  let body = "";

  if (d.summary)               body += sec("Summary", `<p>${d.summary}</p>`);
  if (d.participants?.length)  body += sec("Participants", `<table><thead><tr><th>Name</th><th>Role</th></tr></thead><tbody>${d.participants.map((p) => `<tr><td>${p.name}</td><td>${p.role || "—"}</td></tr>`).join("")}</tbody></table>`);
  if (d.what_went_well?.length)       body += sec("What Went Well", bul(d.what_went_well));
  if (d.what_needs_work?.length)      body += sec("What Needs Work", bul(d.what_needs_work));
  if (d.what_is_not_needed?.length)   body += sec("What Is Not Needed", bul(d.what_is_not_needed));
  if (d.existing_solutions_to_use?.length) body += sec("Existing Solutions", `<table><thead><tr><th>Solution</th><th>Context</th></tr></thead><tbody>${d.existing_solutions_to_use.map((s) => `<tr><td><strong>${s.solution}</strong></td><td>${s.context}</td></tr>`).join("")}</tbody></table>`);
  if (d.next_steps?.length)    body += sec("Next Steps", `<table><thead><tr><th>Action</th><th>Owner</th><th>Due</th></tr></thead><tbody>${d.next_steps.map((s) => `<tr><td>${s.action}</td><td>${s.owner}</td><td>${s.due}</td></tr>`).join("")}</tbody></table>`);
  if (d.transcript_condensed)  body += sec("Condensed Transcript", `<p style="color:#444;line-height:1.7;white-space:pre-wrap">${d.transcript_condensed}</p>`);

  openPdf(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><title>${clientName} — Meeting Summary</title><style>${BASE_STYLES}</style></head><body><header><h1>${clientName} — Meeting Summary</h1><p>Generated by Shinko1 · ${date}</p></header>${body}</body></html>`);
}

// ── CPS PDF ───────────────────────────────────────────────────────────────────

interface CpsStakeholder { name: string; role: string; influence: string }
interface CpsComponent   { name: string; owner: string; purpose: string }
interface CpsRisk        { risk: string; impact: string; likelihood: string; mitigation: string }
interface CpsTradeOff    { decision: string; chosen: string; rationale: string; alternatives?: string }
interface CpsOption      { option: string; rationale: string; ruled_out_reason: string }
interface CpsNextStep    { action: string; owner: string; due: string }
interface CpsChangeLog   { date: string; version: string; summary_of_changes: string }
interface CpsOutput {
  meta?: { client?: string; project?: string; status?: string; version?: string; last_updated?: string; meeting_inputs?: string[] }
  context?: { trigger?: string; environment?: string; organisation?: string; stakeholders?: CpsStakeholder[] }
  problem?: { primary_problem?: string; problem_detail?: string; constraints?: string[]; key_challenges?: string[]; what_has_been_tried?: string[] }
  ideation?: { open_questions?: string[]; options_considered?: CpsOption[] }
  solution?: { approach?: string; strategy?: string; components?: CpsComponent[]; risk_assessment?: CpsRisk[]; trade_off_analysis?: CpsTradeOff[] }
  next_steps?: CpsNextStep[]
  change_log?: CpsChangeLog[]
}

export function exportCpsPdf(raw: string) {
  let d: CpsOutput;
  try { d = JSON.parse(raw); } catch { return plainTextPdf("CPS Document", "Context · Problem · Solution", raw); }

  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  let body = "";

  // Meta bar
  if (d.meta) {
    const meta = [
      d.meta.client       ? `<span><strong>Client:</strong> ${d.meta.client}</span>` : "",
      d.meta.status       ? `<span><strong>Status:</strong> ${d.meta.status}</span>` : "",
      d.meta.version      ? `<span><strong>Version:</strong> ${d.meta.version}</span>` : "",
      d.meta.last_updated ? `<span><strong>Updated:</strong> ${d.meta.last_updated}</span>` : "",
    ].filter(Boolean).join("");
    if (meta) body += `<div class="meta-row">${meta}</div>`;
    if (d.meta.meeting_inputs?.length) body += `<p style="font-size:10pt;color:#555;margin-bottom:20px"><strong>Meeting inputs:</strong> ${d.meta.meeting_inputs.join("; ")}</p>`;
  }

  // Context
  if (d.context) {
    let html = "";
    if (d.context.trigger)      html += `<h3>Trigger</h3><p>${d.context.trigger}</p>`;
    if (d.context.environment)  html += `<h3>Environment</h3><p>${d.context.environment}</p>`;
    if (d.context.organisation) html += `<h3>Organisation</h3><p>${d.context.organisation}</p>`;
    if (d.context.stakeholders?.length) html += `<h3>Stakeholders</h3><table><thead><tr><th>Name</th><th>Role</th><th>Influence</th></tr></thead><tbody>${d.context.stakeholders.map((s) => `<tr><td><strong>${s.name}</strong></td><td>${s.role}</td><td>${s.influence}</td></tr>`).join("")}</tbody></table>`;
    if (html) body += sec("Context", html);
  }

  // Problem
  if (d.problem) {
    let html = "";
    if (d.problem.primary_problem) html += `<h3>Primary Problem</h3><p>${d.problem.primary_problem}</p>`;
    if (d.problem.problem_detail)  html += `<h3>Detail</h3><p>${d.problem.problem_detail}</p>`;
    if (d.problem.constraints?.length)      html += `<h3>Constraints</h3>${bul(d.problem.constraints)}`;
    if (d.problem.key_challenges?.length)   html += `<h3>Key Challenges</h3>${bul(d.problem.key_challenges)}`;
    if (d.problem.what_has_been_tried?.length) html += `<h3>What Has Been Tried</h3>${bul(d.problem.what_has_been_tried)}`;
    if (html) body += sec("Problem", html);
  }

  // Ideation
  if (d.ideation) {
    let html = "";
    if (d.ideation.open_questions?.length) html += `<h3>Open Questions</h3>${bul(d.ideation.open_questions)}`;
    if (d.ideation.options_considered?.length) html += `<h3>Options Considered</h3><table><thead><tr><th>Option</th><th>Rationale</th><th>Ruled Out Because</th></tr></thead><tbody>${d.ideation.options_considered.map((o) => `<tr><td><strong>${o.option}</strong></td><td>${o.rationale}</td><td>${o.ruled_out_reason}</td></tr>`).join("")}</tbody></table>`;
    if (html) body += sec("Ideation", html);
  }

  // Solution
  if (d.solution) {
    let html = "";
    if (d.solution.approach) html += `<h3>Approach</h3><p>${d.solution.approach}</p>`;
    if (d.solution.strategy) html += `<h3>Strategy</h3><p>${d.solution.strategy}</p>`;
    if (d.solution.components?.length) html += `<h3>Components</h3><table><thead><tr><th>Component</th><th>Owner</th><th>Purpose</th></tr></thead><tbody>${d.solution.components.map((c) => `<tr><td><strong>${c.name}</strong></td><td>${c.owner}</td><td>${c.purpose}</td></tr>`).join("")}</tbody></table>`;
    if (d.solution.risk_assessment?.length) html += `<h3>Risk Assessment</h3><table><thead><tr><th>Risk</th><th>Impact</th><th>Likelihood</th><th>Mitigation</th></tr></thead><tbody>${d.solution.risk_assessment.map((r) => `<tr><td>${r.risk}</td><td>${r.impact}</td><td>${r.likelihood}</td><td>${r.mitigation}</td></tr>`).join("")}</tbody></table>`;
    if (d.solution.trade_off_analysis?.length) html += `<h3>Trade-off Analysis</h3><table><thead><tr><th>Decision</th><th>Chosen</th><th>Rationale</th></tr></thead><tbody>${d.solution.trade_off_analysis.map((t) => `<tr><td>${t.decision}</td><td><strong>${t.chosen}</strong></td><td>${t.rationale}</td></tr>`).join("")}</tbody></table>`;
    if (html) body += sec("Solution", html);
  }

  // Next Steps
  if (d.next_steps?.length) body += sec("Next Steps", `<table><thead><tr><th>Action</th><th>Owner</th><th>Due</th></tr></thead><tbody>${d.next_steps.map((s) => `<tr><td>${s.action}</td><td>${s.owner}</td><td>${s.due}</td></tr>`).join("")}</tbody></table>`);

  // Change Log
  if (d.change_log?.length) body += sec("Change Log", `<table><thead><tr><th>Version</th><th>Date</th><th>Changes</th></tr></thead><tbody>${d.change_log.map((c) => `<tr><td>${c.version}</td><td>${c.date}</td><td>${c.summary_of_changes}</td></tr>`).join("")}</tbody></table>`);

  const title = d.meta?.project ?? "CPS Document";
  openPdf(`<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"/><title>${title}</title><style>${BASE_STYLES}</style></head><body><header><h1>${title}</h1><p>Context · Problem · Solution  ·  Generated by Shinko1 · ${date}</p></header>${body}</body></html>`);
}
