import { NextRequest, NextResponse } from "next/server";
import { google } from "googleapis";
import { getDriveAuth } from "../_auth";
import { Readable } from "stream";
import { unified } from "unified";
import remarkParse from "remark-parse";
import remarkGfm from "remark-gfm";
import remarkRehype from "remark-rehype";
import rehypeStringify from "rehype-stringify";
import remarkBreaks from "remark-breaks";
import fs from "fs";
import path from "path";

const DOC_STYLES = `
  body {
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    font-size: 11pt; color: #111; padding: 40px 48px; max-width: 900px; margin: auto;
  }
  .doc-header-table { width: 100%; border-collapse: collapse; border-bottom: 2px solid #111; padding-bottom: 14px; margin-bottom: 28px; }
  .doc-header-table td { padding: 0; border: none; vertical-align: middle; }
  .doc-title { font-size: 20pt; font-weight: 700; letter-spacing: -0.02em; margin: 0 0 4px 0; }
  .doc-subtitle { font-size: 10pt; color: #555; margin: 0; }
  .doc-logo { text-align: right; }
  .doc-logo img { width: 96px; height: auto; display: block; margin-left: auto; }
  h1 { font-size: 16pt; font-weight: 700; margin: 20px 0 10px 0; }
  h2 {
    font-size: 10pt; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase;
    color: #555; border-bottom: 1px solid #e4e4e4; padding-bottom: 5px; margin: 24px 0 10px 0;
  }
  h3 { font-size: 11pt; font-weight: 600; margin: 16px 0 6px 0; }
  h4 { font-size: 10.5pt; font-weight: 600; margin: 12px 0 4px 0; }
  p  { line-height: 1.7; margin: 0 0 12px 0; }
  ul, ol { padding-left: 22px; margin: 0 0 12px 0; }
  li { margin-bottom: 6px; line-height: 1.65; }
  table { width: 100%; border-collapse: collapse; font-size: 10.5pt; margin: 0 0 16px 0; }
  th {
    text-align: left; font-size: 9pt; font-weight: 600; letter-spacing: 0.04em;
    text-transform: uppercase; color: #555; padding: 8px 12px;
    background: #f7f7f7; border-bottom: 2px solid #ddd;
  }
  td { padding: 8px 12px; border-bottom: 1px solid #f0f0f0; vertical-align: top; line-height: 1.55; }
  tr:last-child td { border-bottom: none; }
  pre { background: #f7f7f7; border: 1px solid #e4e4e4; border-radius: 4px;
        padding: 12px 14px; font-size: 9.5pt; overflow-x: auto; margin: 0 0 14px 0; }
  code { font-family: "SF Mono", Menlo, monospace; font-size: 9.5pt; background: #f3f3f3; padding: 1px 4px; border-radius: 3px; }
  pre code { background: none; padding: 0; }
  blockquote { border-left: 3px solid #ccc; padding: 4px 0 4px 14px; color: #555; margin: 0 0 12px 0; }
  hr { border: none; border-top: 1px solid #e4e4e4; margin: 24px 0; }
  strong { font-weight: 600; }
  .content { margin-top: 4px; }
`;

function getLogoBase64(): string {
  try {
    const logoPath = path.join(process.cwd(), "public", "shinko-logo.png");
    const data = fs.readFileSync(logoPath);
    return `data:image/png;base64,${data.toString("base64")}`;
  } catch {
    return "";
  }
}

async function markdownToHtml(md: string, title: string): Promise<string> {
  const result = await unified()
    .use(remarkParse)
    .use(remarkGfm)
    .use(remarkBreaks)
    .use(remarkRehype)
    .use(rehypeStringify)
    .process(md);

  const date = new Date().toLocaleDateString("en-GB", { day: "numeric", month: "long", year: "numeric" });
  const logoSrc = getLogoBase64();
  const logoRow = logoSrc
    ? `<tr>
        <td style="text-align:right;padding:0 0 10px 0;border:none;">
          <img src="${logoSrc}" alt="Shinko1" width="96" style="width:96px;height:auto;display:inline-block;" />
        </td>
       </tr>`
    : "";

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>${title}</title>
  <style>${DOC_STYLES}</style>
</head>
<body>
  <table style="width:100%;border-collapse:collapse;border-bottom:2px solid #111;margin-bottom:28px;">
    ${logoRow}
    <tr>
      <td style="padding:0 0 14px 0;border:none;">
        <p style="font-size:20pt;font-weight:700;letter-spacing:-0.02em;margin:0 0 4px 0;">${title}</p>
        <p style="font-size:10pt;color:#555;margin:0;">Generated by Shinko1 &middot; ${date}</p>
      </td>
    </tr>
  </table>
  <div class="content">
    ${String(result)}
  </div>
</body>
</html>`;
}

export async function POST(req: NextRequest) {
  const driveAuth = getDriveAuth(req);
  if (!driveAuth) return NextResponse.json({ error: "Not connected to Google Drive" }, { status: 401 });

  const { transcript, folderId, fileName, fileId } = await req.json() as {
    transcript: string;
    folderId: string;
    fileName?: string;
    fileId?: string;
  };

  if (!transcript) return NextResponse.json({ error: "Missing transcript" }, { status: 400 });

  const drive = google.drive({ version: "v3", auth: driveAuth.auth });

  const baseName = (fileName ?? `transcript-${new Date().toISOString().replace(/[:.]/g, "-")}`).replace(/\.md$/, "");
  const html = await markdownToHtml(transcript, baseName);

  try {
    let file;

    if (fileId) {
      // ── Update existing Google Doc in-place ──────────────────────────────
      const stream = Readable.from([html]);
      file = await drive.files.update({
        fileId,
        requestBody: { name: baseName },
        media: { mimeType: "text/html", body: stream },
        fields: "id,name,webViewLink",
        supportsAllDrives: true,
      });
    } else {
      // ── Create new Google Doc ────────────────────────────────────────────
      if (!folderId) return NextResponse.json({ error: "Missing folderId" }, { status: 400 });
      const stream = Readable.from([html]);
      file = await drive.files.create({
        requestBody: {
          name: baseName,
          parents: [folderId],
          mimeType: "application/vnd.google-apps.document",
        },
        media: { mimeType: "text/html", body: stream },
        fields: "id,name,webViewLink",
        supportsAllDrives: true,
      });
    }

    const res = NextResponse.json({
      id: file.data.id,
      name: file.data.name,
      url: file.data.webViewLink,
    });
    driveAuth.setTokenCookies(res);
    return res;
  } catch (err: unknown) {
    const message = err instanceof Error ? err.message : String(err);
    console.error("[drive/save]", err);
    return NextResponse.json({ error: message }, { status: 500 });
  }
}
